package com.eswaraj.domain.validator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.eswaraj.domain.nodes.Person;
import com.eswaraj.domain.util.ValidCharacters;
import com.eswaraj.domain.validator.exception.ValidationException;

@Component
public class PersonValidator extends BaseValidator<Person>{

	@Autowired
	public PersonValidator(ValidationManager validationManager) {
		super(Person.class, validationManager);
	}

	@Override
    public void validateBeforeSave(Person person) throws ValidationException {
		checkIfEmpty("Name", person.getName(),"Persons name can not be Null or Empty");
		//checkIfEmpty("Email", person.getEmail(),"Person's email cannot be empty or null");
		checkLength(person.getName(), "Person name should be of length between 2 and 64", 2, 64);
		checkAcceptedCharacters(person.getName(), "Person's name can only contain alphabets", ValidCharacters.NAME);
		if(person.getEmail() != null && !person.getEmail().trim().equals("")){
			checkAcceptedCharacters(person.getEmail(), "Invalid email", ValidCharacters.EMAIL);	
		}
		
	}

	@Override
    public void validateBeforeDelete(Person person) throws ValidationException {
		
	}
}

[
 
 {
     "id": 85821,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manoj Tiwari",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85821.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85823,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Udit Raj",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85823.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85826,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Meenakshi Lekhi",
     "biodata": "",
     "dob": null,
     "gender": "female",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85826.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85829,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Pravesh Verma",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85829.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85832,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Harsh Vardhan",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85832.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85792,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "pranab mukherjee",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/null.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85831,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Mahesh Giri",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85831.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85888,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Narendra Modi",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85888.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85920,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Mahendra Nagpal",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85920.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85925,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Mahinder Yadav",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/null.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85931,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Om Prakash Sharma",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85931.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85944,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Pawan Sharma",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85944.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85947,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Ramesh Bidhuri",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85947.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85950,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Raju Dhingan",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": null,
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85950.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85953,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Nand Kishore Garg",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85953.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85957,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Harish Khanna",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85957.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85960,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Jarnail Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85960.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85963,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Jai Kishan",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85963.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85968,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Bandana Kumari",
     "biodata": "",
     "dob": null,
     "gender": "female",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85968.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85970,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Satyender Kumar Jain",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85970.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85972,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Jitender Singh Shunty",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85972.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85980,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Dharmender Singh Koli",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85980.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85986,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Chaudhary Mateen Ahmad",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85986.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85988,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Dinesh Mohaniya",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85988.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85990,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Som Dutt Sharma",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85990.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 85999,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Jitender Kumar",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/85999.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86003,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Rajesh Garg Rohiniwala",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86003.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86007,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Kulwant Rana",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86007.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86009,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manjinder Singh Sirsa",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86009.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86026,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "R.P.Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86026.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86030,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Anil Kumar Sharma",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86030.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86034,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manish Sisodia",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86034.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86036,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Veena Anand",
     "biodata": "",
     "dob": null,
     "gender": "female",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86036.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86038,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Dharm Dev Solanki",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86038.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86034,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manish Sisodia",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86034.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86041,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Ram Kishan Singhal",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86041.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86043,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Ashok Kumar",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86043.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86045,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Naresh Gaur",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86045.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86047,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Rambir Singh Bidhuri",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86047.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86049,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Devender Yadav",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/null.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86051,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Haroon Yusuf",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86051.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86053,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Gugan Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86053.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86055,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Sat Prakash Rana",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86055.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86057,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Sanjeev Jha",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86057.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86059,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Parlad Singh Sawhney",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86059.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86061,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Brahm Singh Tanwar",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86061.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86063,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Surender Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86063.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86065,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Prakash",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86065.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86067,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Parduymn Rajput",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86067.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86069,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Arvinder Singh Lovely",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86069.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86071,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Sahib Singh Chauhan",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86071.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86073,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Ranjeet Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86073.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86075,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Saurabh Bharadwaj",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86075.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86077,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Jagdeep Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86077.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86079,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Jagdish Mukhi",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86079.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86081,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": " Maninder Singh Dhir",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86081.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86084,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Harmeet Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86084.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86086,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Mohan Singh Bisht",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86086.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86088,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Vishesh Ravi",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86088.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86090,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Madan Lal",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86090.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86092,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Anil Jha",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86092.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86094,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manoj Kumar",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86094.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86096,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Harsh Vardhan",
     "biodata": "<span class=\"Apple-tab-span\" style=\"white-space:pre\">\t\t\t\t</span>",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86096.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86096,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Harsh Vardhan",
     "biodata": "<span class=\"Apple-tab-span\" style=\"white-space:pre\">\t\t\t\t</span>",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86096.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86099,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Vinod Kumar Binny",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86099.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86101,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Girish Soni",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86101.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86103,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Asif Mohd. Khan",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86103.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86104,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Somnath Bharti",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86104.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86106,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Neel Daman Khatri",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86106.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86109,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Manoj Kumar Shokeen",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86109.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86111,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Ajeet Singh Kharkhari",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86111.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86114,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Hasan Ahmed",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86114.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86117,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Rambir Shokeen",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86117.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86124,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Subhash Sachdeva",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86124.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86126,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Akhilesh Pati Tripathi",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86126.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86128,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Parvesh Sahib Singh",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86128.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86131,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Rajesh Gahlot",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86131.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86137,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Shoaib Iqbal",
     "biodata": "",
     "dob": null,
     "gender": "male",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86137.jpg",
     "voterId": "",
     "address": null
 },
 {
     "id": 86139,
     "dateCreated": null,
     "dateModified": null,
     "creatorId": null,
     "modifierId": null,
     "externalId": null,
     "name": "Rakhi Birla",
     "biodata": "",
     "dob": null,
     "gender": "female",
     "email": "",
     "landlineNumber1": "",
     "landlineNumber2": "",
     "mobileNumber1": "",
     "mobileNumber2": "",
     "profilePhoto": "https://s3-us-west-2.amazonaws.com/eswaraj-dev/profile/86139.jpg",
     "voterId": "",
     "address": null
 }
]